spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.jdbc-url=jdbc:mysql://localhost:13306/board?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

mybatis.mapper-locations=classpath:mappers/*.xml

# redis
spring.cache.type=redis
spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.data.redis.password=
spring.data.redis.repositories.enabled=false

server.servlet.session.tracking-modes=cookie
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=false


expire.defaultTime=3600



springdoc.swagger-ui.csrf.enabled=false
springdoc.swagger-ui.with-credentials=true
